# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YoutubePlayerView'
  pod 'Alamofire', '~> 5.4.3'
  pod 'SwiftyJSON', '~> 5.0.0'

  # Pods for MovieListApp

  target 'MovieListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieListAppUITests' do
    # Pods for testing
  end

end
